service: culqi

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: sa-east-1

#  environment:
#    variable1: value1

functions:
  generarToken:
    handler: build/handler.generarToken
    events:
      - httpApi:
          path: /tokens
          method: POST
  procesarCargo:
    handler: build/handler.procesarCargo
    events:
      - httpApi:
          path: /tokens
          method: GET
